[package]
name = "k-as-a-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.53.1"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
libc = "0.2.140"
