[project]
name = "k-as-a-library"
version = "0.1.0"
source = "k-src"

[targets.llvm]
backend = "llvm"
main-file = "arithmetic.k"
llvm-kompile-type = "c"
llvm-kompile-output = "libarithmetic"
gen-bison-parser = true
bison-parser-library = true
